### PR TITLE
google-vertexai: release 2.0.10

### PR DESCRIPTION
**Pull request by efriis**

### CODE REVIEW

**Review by baskaryan — APPROVED** [review]

**Comment by ostefano** [comment]
@efriis @baskaryan  is this released? PyPI (https://pypi.org/project/langchain-google-vertexai/#files) does not seem to have the updated package.

**Comment by efriis** [comment]
attempting again! Looks like the release hit some kind of rate limit. thanks for ping!

https://github.com/langchain-ai/langchain-google/actions/workflows/_release.yml

**Comment by ostefano** [comment]
@efriis looks like vertexai failed again :(

**Comment by lkuligin** [comment]
released

**Pull request merged**
