### PR TITLE
Incrementing langchain-google-vertexai to 1.0.5

### PR DESCRIPTION
**Pull request by tdigangi**
Starting the release for `pip install langchain-google-vertexai==1.0.5`

### CODE REVIEW

**Comment by lkuligin** [comment]
what's the purpose of this PR?

**Comment by tdigangi** [comment]
Purpose of the PR is to initiate a release of vertexai to 1.0.5 as the release [/libs/genai/v1.0.5)](https://github.com/langchain-ai/langchain-google/releases/tag/libs%2Fgenai%2Fv1.0.5) does not include some of the features covered in its release.

**Comment by thomasmenard-oa** [comment]
@lkuligin can you validate the release please. We need it on our side to be able to leverage Gemini multimodal using type:media 
Thanks

**Pull request closed without merging**
