### PR TITLE
anthropic [patch] add tool_result type to ToolMessage content

### PR DESCRIPTION
**Pull request by rvndbalaji**
Patching anthropic tool calls from the following PRs from langchain main repo

* https://github.com/langchain-ai/langchain/pull/22687
* https://github.com/langchain-ai/langchain/pull/22721

### CODE REVIEW

**Comment by rvndbalaji** [comment]
@lkuligin 
The integration test is failing due to Resource exhaustion

**Comment by rvndbalaji** [comment]
@lkuligin  Any timeline on when this will be available as part of the next release?
I wish to use this in my work, and im in dire need of tool calling 

(Right now im closing the master branch and creating a whl file)
I'd like a new released version

**Comment by lkuligin** [comment]
we target the beginning of the next week for a release.

P.S. just in case, maybe it's an easier way to install from main (but remember to uninstall the previously install version first, otherwise `pip` might not catch the update since the version is the same):
`pip install --upgrade "git+https://github.com/langchain-ai/langchain-google.git#subdirectory=libs/vertexai"`

**Pull request merged**
