### PR TITLE
Added  anthropic support for bind_tools, with_structured_output & tool-parsing

### PR DESCRIPTION
**Pull request by rvndbalaji**
*My very-very first open source contribution*

Therefore, please do let me know if any changes are required
I personally feel like this is incomplete for some reason, but do let me know

Related Issues 
* https://github.com/langchain-ai/langchain-google/issues/268
* https://github.com/langchain-ai/langchain-google/issues/176

I did the following

1. Copy pasted the logic from [langchain_anthropic.](https://github.com/langchain-ai/langchain/blob/master/libs/partners/anthropic/langchain_anthropic/chat_models.py) 
2. I was unable to test my changes locally . But I did create a custom inherited class with the overridden `bind_tools` and `with_structured_output` methods in jupyter notebooks and it worked- I don't know how test this locally, so I'll be happy to do so if required
3. If i've made a mistake, please let me know and ill make the required changes

FYI - @lkuligin

### CODE REVIEW

**Review by lkuligin — CHANGES_REQUESTED** [review]
thanks a lot for your contribution!
please, fix linting errors and an integration test.

also I believe it's worth adding a unit tests to check for history parsing

**Comment by rvndbalaji** [comment]
@lkuligin I have run `make format`, `make lint` and `make tests` locally and everything passed
I did notice a few deprecation warnings

Could you please run the workflow again?

**Comment by rvndbalaji** [comment]
@lkuligin  Hey, so the unit tests failed because the packages were updated in my local and I have now modified them in the .toml file as well

I ran the `make tests` and 64 tests passed with 2 depr. warnings

I was unable to run the `poetry run pytest --release tests/integration_tests` locally, because my corp wifi is blocking the grpc requests

Please run the workflow again, and hopefully third time's the charm :D

**Comment by lkuligin** [comment]
I added an integration and a few small fixes.
@rvndbalaji I'm going to merge it, but it would be great if you could work on another PR with adding unit tests for parser (and also for parsing output and preparing tools calls). Thanks a lot!

**Review by lkuligin — APPROVED** [review]

**Pull request merged**
