### PR TITLE
Adding property to private_service_connect_ip_address to endpoint VectorSearchVectorStore

### PR DESCRIPTION
**Pull request by tdigangi**
Add private_service_connect_ip_address to VectorSearchVectorStore via the from_components() method. Added placeholder integration test for private PSC endpoint. 

Please provide guidance on how to update integration tests. Also if you wish to add more [MatchingEngineIndexEndpoint properties](https://cloud.google.com/python/docs/reference/aiplatform/latest/google.cloud.aiplatform.MatchingEngineIndexEndpoint#properties) in this PR or have a opinion on a more complex data structure(I.E. via kwargs or dict) to add properties provide this guidance and I will update accordingly.

### CODE REVIEW

**Comment by tdigangi** [comment]
It looks like from_components is reliant upon a endpoint existing within the environment, thus I have put it in an integration test. I started to craft a unit test, but paused when I saw that [endpoint](https://github.com/langchain-ai/langchain-google/pull/203/files#diff-87f6faa533a83ab27a6327f01da041e79e1c7d6e92b835d49b60a53c4874c2a4L302) requires an endpoints exists. 

I believe it is an integration needed but this would have to be part of the infra setup used when these test execute. Let me know how you wish to proceed.

**Comment by tdigangi** [comment]
I am unable to debug the [cloud build error](https://github.com/langchain-ai/langchain-google/pull/203/checks?check_run_id=24950482955) due to a lack of permission on the project in which they are placed. My best guess would be the [endpoint is not set up with PSC](https://cloud.google.com/vertex-ai/docs/general/vertex-psc-vector-search#create_the_consumer_endpoint).

**Comment by lkuligin** [comment]
@tdigangi I'm sorry for the delay, I'm looking for smbd from the Vertex Vector Store team to take a look and help with the review.

**Review by lingyinw — APPROVED** [review]

**Review by lkuligin — APPROVED** [review]

**Pull request merged**
