### PR TITLE
community: Change post-filters to pre-filters in BigQueryVectorStore

### PR DESCRIPTION
**Pull request by francislan**
## PR Description

BigQueryVectorStore's `_create_filters` are post-filters. Now that BigQuery Vector Search supports pre-filtering on stored columns (https://cloud.google.com/bigquery/docs/vector-index#stored-columns), we can change all post-filters to pre-filters.

Note that this requires storing the columns that are referenced by the pre-filter. This cannot be done in Langchain yet (have to use the BQ CLI/UI directly). If the required columns are not stored, then the pre-filters will act as post-filters.

## Type

🆕 New Feature

## Changes(optional)

Change the vector search query from:

```sql
SELECT *
FROM VECTOR_SEARCH(
  Table <table>,
  ...)
WHERE <filter>
```

to 

```sql
SELECT *
FROM VECTOR_SEARCH(
  (SELECT * FROM <table> WHERE <filter>),
  ...)
```

## Testing(optional)

Run unit and integration tests.

### CODE REVIEW

**Review by eliasecchig — APPROVED** [review]
LGTM

**Comment by eliasecchig** [comment]
@lkuligin for final approval

**Comment by lkuligin** [comment]
we should start increasing the test coverage, please. It should have at least a unit test.

**Comment by francislan** [comment]
> we should start increasing the test coverage, please. It should have at least a unit test.

I know we should have more unit and integration tests, but can we do that later once we have a owner for BigQueryVectorStore? I struggled for 2 hours to write a unit tests using mocks and was not able to make it work (I'm neither proficient in Python nor Langchain infra).

**Comment by francislan** [comment]
@lkuligin What do you think? Can we add more testing later?

**Comment by lkuligin** [comment]
@eliasecchig merging for now, but, please, plan to improve the testing coverage for this component in the future

**Review by lkuligin — APPROVED** [review]

**Pull request merged**
