### PR TITLE
Added new gemini family model MedLM-Large-1.5-preview

### PR DESCRIPTION
**Pull request by smannathan**
Google has released a new model, **medlm-large-1.5-preview**, as part of the **Gemini family**.

Changes:
- Updated _utils.py to incorporate the new model.
- Modified test cases to reflect the updates.

Please review the changes and provide feedback.

### CODE REVIEW

**Comment by smannathan** [comment]
Would you please check if you have access to the new model? 

"Project `546814358370` is not allowed to use Publisher Model `projects/llm-integration-tests/locations/us-central1/publishers/google/models/medlm-large-1.5-preview`"

**Comment by smannathan** [comment]
Would you please check if you have access to the new model? 

"Project `546814358370` is not allowed to use Publisher Model `projects/llm-integration-tests/locations/us-central1/publishers/google/models/medlm-large-1.5-preview`"

**Comment by smannathan** [comment]
Pipeline GCP project does not have access to new models. 

"Project `546814358370` is not allowed to use Publisher Model `projects/llm-integration-tests/locations/us-central1/publishers/google/models/medlm-large-1.5-preview`"

Should i keep the integration tests or remove them?

**Comment by smannathan** [comment]
> Pipeline GCP project does not have access to new models.
> 
> "Project `546814358370` is not allowed to use Publisher Model `projects/llm-integration-tests/locations/us-central1/publishers/google/models/medlm-large-1.5-preview`"
> 
> Should i keep the integration tests or remove them?

I removed the integration test cases now.

**Review by lkuligin — APPROVED** [review]

**Review by lkuligin — APPROVED** [review]

**Pull request merged**
